### ISSUE TITLE
Request: show current temperature

### ISSUE THREAD

**Issue by andig** [georg90/pimatic-max-thermostat#15]
As I understand the UI, the +/- temp control shows the desired temperature when in manual mode. According to EQ3, max thermostat does also measure temp. Can this temp be shown in the device?

**Comment by pimagical** [comment]
@andig @sweetpi use the MaxWallThermostat device with a MaxHeatThermostat rfaddress then you have the actual temperature of the heat thermostat but it is around 2 degrees higher than the wall thermostat due the location near the radiator. Proposed a change for the documentation: https://github.com/pimatic/pimatic-max/pull/7

**Comment by georg90** [comment]
Please use:  https://github.com/pimatic/pimatic-max
