### ISSUE TITLE
Implement an 'on demand' option to prevent permanent connection of the plugin to MAX!Cube

### ISSUE THREAD

**Issue by Kingsammy** [georg90/pimatic-max-thermostat#22]
The 'pimatic-max-thermostat' plugin is permanent connected with the MAX!Cube hardware. So it is impossible to connect to the Cube with other software a the same time.
I suggest to implement an  "on demand" option. The plugin should only connect to MAX!Cube when it is reading temperatures (every 5 minutes) and e.g. when a command is send.

**Comment by georg90** [comment]
Please use: https://github.com/pimatic/pimatic-max
