### ISSUE TITLE
Pimatic reconnect

### ISSUE THREAD

**Issue by ghost** [georg90/pimatic-max-thermostat#24]
Hello,
First I want to thanks for this plugin which I am using for several months. But I was one problem with lan maxcube. When I restart maxcube, Pimatic doesn't reconnect to it. I must restart pimatic for successfull connection. It is possible to implement autoreconnect possibilities to this plugin?

Thank you.

**Comment by georg90** [comment]
https://github.com/georg90/pimatic-max-thermostat/issues/23
